version: '3.8'
services:
  web1:
    build : app1/
    ports:
      - "8001:8000"

  web2:
    build : app2/
    ports:
      - "8002:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
